"""empty message

Revision ID: 0dfe2baf49d8
Revises: 
Create Date: 2021-10-18 23:51:01.455333

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0dfe2baf49d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('expense_item', sa.String(length=20), nullable=False),
    sa.Column('expense_value', sa.Float(), nullable=False),
    sa.Column('expense_item_category', sa.String(length=20), nullable=False),
    sa.Column('expense_source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_expense_expense_date'), 'budget_expense', ['expense_date'], unique=False)
    op.create_table('budget_revenue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revenue_date', sa.DateTime(), nullable=False),
    sa.Column('revenue_value', sa.Float(), nullable=False),
    sa.Column('revenue_source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_revenue_revenue_date'), 'budget_revenue', ['revenue_date'], unique=False)
    op.create_table('budget_saving',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saving_date', sa.DateTime(), nullable=False),
    sa.Column('saving_value', sa.Float(), nullable=False),
    sa.Column('saving_source', sa.String(length=20), nullable=False),
    sa.Column('saving_reason', sa.String(length=20), nullable=False),
    sa.Column('saving_action', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_saving_saving_date'), 'budget_saving', ['saving_date'], unique=False)
    op.create_table('budget_utilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilities_date', sa.DateTime(), nullable=False),
    sa.Column('utilities_rent_value', sa.Float(), nullable=False),
    sa.Column('utilities_energy_value', sa.Float(), nullable=False),
    sa.Column('utilities_satellite_value', sa.Float(), nullable=False),
    sa.Column('utilities_maintenance_value', sa.Float(), nullable=False),
    sa.Column('utilities_info', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_utilities_utilities_date'), 'budget_utilities', ['utilities_date'], unique=False)
    op.create_table('saving_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categories', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categories')
    )
    op.create_table('saving_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('items', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('items')
    )
    op.create_table('saving_reason',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saving_reason', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saving_reason')
    )
    op.create_table('saving_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sources', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sources')
    )
    op.create_table('savings_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saving_accounts', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saving_accounts')
    )
    op.create_table('savings_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saving_action_type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saving_action_type')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_created'), 'posts', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_created'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('user')
    op.drop_table('savings_actions')
    op.drop_table('savings_accounts')
    op.drop_table('saving_sources')
    op.drop_table('saving_reason')
    op.drop_table('saving_items')
    op.drop_table('saving_categories')
    op.drop_index(op.f('ix_budget_utilities_utilities_date'), table_name='budget_utilities')
    op.drop_table('budget_utilities')
    op.drop_index(op.f('ix_budget_saving_saving_date'), table_name='budget_saving')
    op.drop_table('budget_saving')
    op.drop_index(op.f('ix_budget_revenue_revenue_date'), table_name='budget_revenue')
    op.drop_table('budget_revenue')
    op.drop_index(op.f('ix_budget_expense_expense_date'), table_name='budget_expense')
    op.drop_table('budget_expense')
    # ### end Alembic commands ###
