"""empty message

Revision ID: 65096e7dbf5d
Revises: abe1b550000f
Create Date: 2021-12-14 00:04:33.463929

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '65096e7dbf5d'
down_revision = 'abe1b550000f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_encode_decode_parse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_date', sa.Date(), nullable=False),
    sa.Column('raw_url', sa.String(length=1000), nullable=False),
    sa.Column('encode_option', sa.String(length=10), nullable=True),
    sa.Column('encoding', sa.String(length=10), nullable=True),
    sa.Column('url_query', sa.String(length=1000), nullable=True),
    sa.Column('parse_only', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_encode_decode_parse_url_date'), 'url_encode_decode_parse', ['url_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_encode_decode_parse_url_date'), table_name='url_encode_decode_parse')
    op.drop_table('url_encode_decode_parse')
    # ### end Alembic commands ###
