"""empty message

Revision ID: a3bddfff1704
Revises: 65096e7dbf5d
Create Date: 2021-12-14 00:10:10.442118

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a3bddfff1704'
down_revision = '65096e7dbf5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_encode_decode_parse', sa.Column('parse_only', sa.BOOLEAN(), nullable=False))
    op.add_column('url_encode_decode_parse', sa.Column('url_query', sa.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
