"""empty message

Revision ID: abe1b550000f
Revises: 0dfe2baf49d8
Create Date: 2021-10-24 16:52:21.511913

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'abe1b550000f'
down_revision = '0dfe2baf49d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
