skip_macro_keys = ['title', 'isBuiltin', 'pill', 'nameProperty', 'function', 'infoKey']
skip_tag_keys = ['pill', 'property', 'nameProperty', 'title', 'function', 'infoKey', 'teardown_tags',
                 'setup_tags', '_sequence', '_conditions', '_blocking', 'exportType']
skip_trigger_keys = ['gtm.triggerGroup', '__tg']
triggers_not_tags = ['__tl', '__tg', '__cl', '__lcl', '__evl']
code_snippet_properties = ['vtp_html', 'vtp_javascript']
untracked_macros = ['Environment name']

tags_index = {
    '__paused': {
        'title': 'Paused Tag',
        'nameProperty': 'vtp_originalTagType',
        'pill': 'light'
    },
    '__abtGeneric': {'title': 'AB TASTY Generic Tag'},
    '__adm': {'title': 'Adometry Tag'},
    '__asp': {'title': 'AdRoll Smart Pixel Tag'},
    '__awct': {'title': 'Google Ads Conversion Tracking Tag'},
    '__sp': {'title': 'Google Ads Remarketing Tag'},
    '__awc': {'title': 'Affiliate Window Conversion Tag'},
    '__awj': {'title': 'Affiliate Window Journey Tag'},
    '__baut': {'title': 'Bing Ads Universal Event Tracking'},
    '__bb': {'title': 'Bizrate Insights Buyer Survey Solution'},
    '__bsa': {'title': 'Bizrate Insights Site Abandonment Survey Solution'},
    '__cts': {'title': 'ClickTale Standard Tracking Tag'},
    '__csm': {'title': 'comScore Unified Digital Measurement Tag'},
    '__gclidw': {'title': 'Conversion Linker'},
    '__cegg': {'title': 'Crazy Egg Tag'},
    '__crto': {'title': 'Criteo OneTag'},
    '__html': {
        'title': 'Custom HTML Tag',
        'infoKey': 'vtp_html'
    },
    '__img': {'title': 'Custom Image Tag'},
    '__dstag': {'title': 'DistroScale Tag'},
    '__flc': {'title': 'Floodlight Counter Tag'},
    '__fls': {'title': 'Floodlight Sales Tag'},
    '__m6d': {'title': 'Dstillery Universal Pixel Tag'},
    '__ela': {'title': 'Eulerian Analytics Tag'},
    '__ga': {
        'title': 'Google Analytics Tag',
        'pill': 'warning'
    },
    '__gcs': {'title': 'Google Consumer Surveys Website Satisfaction'},
    '__opt': {'title': 'Google Optimize'},
    '__ts': {'title': 'Google Trusted Stores Tag'},
    '__hjtc': {
        'title': 'Hotjar Tracking Code',
        'pill': 'danger'
    },
    '__infinity': {'title': 'Infinity Call Tracking Tag'},
    '__sca': {'title': 'Intent Media - Search Compare Ads'},
    '__k50Init': {'title': 'K50 tracking tag'},
    '__ll': {'title': 'LeadLab'},
    '__bzi': {'title': 'LinkedIn Tag'},
    '__ljs': {'title': 'Lytics JS Tag'},
    '__ms': {'title': 'Marin Software Tag'},
    '__mpm': {'title': 'Mediaplex - IFRAME MCT Tag'},
    '__mpr': {'title': 'Mediaplex - Standard IMG ROI Tag'},
    '__mf': {'title': 'Mouseflow Tag'},
    '__ndcr': {'title': 'Nielsen DCR Static Lite Tag'},
    '__nudge': {'title': 'Nudge Content Analytics Tag'},
    '__okt': {'title': 'Oktopost Tracking Code'},
    '__omc': {'title': 'Optimise Conversion Tag'},
    '__messagemate': {'title': 'OwnerListens Message Mate'},
    '__pa': {'title': 'Perfect Audience Pixel'},
    '__pc': {'title': 'Personali Canvas'},
    '__placedPixel': {'title': 'Placed'},
    '__pijs': {'title': 'Pulse Insights Voice of Customer Platform'},
    '__qcm': {'title': 'Quantcast Audience Measurement'},
    '__fxm': {'title': 'Rawsoft FoxMetrics'},
    '__scjs': {'title': 'SaleCycle JavaScript Tag'},
    '__scp': {'title': 'SaleCycle Pixel Tag'},
    '__sfc': {'title': 'SearchForce JavaScript Tracking for Conversion Page'},
    '__sfl': {'title': 'SearchForce JavaScript Tracking for Landing Page'},
    '__sfr': {'title': 'SearchForce Redirection Tracking Tag'},
    '__shareaholic': {'title': 'Shareaholic'},
    '__svw': {'title': 'Survicate Widget'},
    '__tdlc': {'title': 'Tradedoubler Lead Conversion Tag'},
    '__tdsc': {'title': 'Tradedoubler Sale Conversion Tag'},
    '__tc': {'title': 'Turn Conversion Tracking Tag'},
    '__tdc': {'title': 'Turn Data Collection Tag'},
    '__twitter_website_tag': {'title': 'Twitter Universal Website Tag'},
    '__ua':
        {'title': 'Universal Analytics Tag',
         'nameProperty': 'vtp_trackType',
         'pill': 'warning'
         },
    '__uslt': {'title': 'Upsellit Global Footer Tag'},
    '__uspt': {'title': 'Upsellit Confirmation Tag'},
    '__vei': {'title': 'Ve Interactive JavaScript Tag'},
    '__veip': {'title': 'Ve Interactive Pixel'},
    '__vdc': {'title': 'VisualDNA Conversion Tag'},
    '__xpsh': {'title': 'Xtremepush'},
    '__yieldify': {'title': 'Yieldify'},
    '__qpx': {'title': 'Quora'},
    '__pntr': {'title': 'Pinterest'},
    '__gaawc': {'title': 'GA4 Configuration', 'pill': 'warning'},
    '__gaawe': {'title': 'GA4 Event', 'pill': 'warning', 'nameProperty': 'vtp_eventName'},
    '_custom_tag_template': {'title': 'Custom Tag Template', 'pill': 'dark', 'nameProperty': 'function'},
    '__ac360': {'title': 'Audience Center 360'},
    '__awcc': {'title': 'Google Ads Calls from Website Conversion', 'pill': 'primary',
               'nameProperty': 'vtp_phoneConversionNumber'},
    '__awud': {'title': 'Google Ads User-provided Data Event', 'pill': 'primary'},
    '__cloud_retail': {'title': 'Google Cloud Retail'},
    '__automl': {'title': 'Google Cloud Recommendations AI'},
    '__gfct': {'title': 'Google Flights Conversion Tracking'},
    '__gfpa': {'title': 'Google Flights Price Accuracy'},
    '__ta': {'title': 'Neustar AdAdvisor'},
    '__qca': {'title': 'Quantcast Advertise'},
    '__tpdpx': {'title': 'Tapad Conversion Pixel'}
}

macros_index = {
    '__k': {'title': 'First Party Cookie', 'nameProperty': 'vtp_name'},
    '__c': {'title': 'Constant', 'nameProperty': 'vtp_value'},
    '__ctv': {'title': 'Container Version', 'isBuiltIn': not False, 'pill': 'primary'},
    '__e': {'title': 'Event', 'isBuiltIn': not False, 'pill': 'primary'},
    '__jsm': {'title': 'Custom JavaScript Variable', 'infoKey': 'vtp_javascript'},
    '__v': {'title': 'Data Layer Var', 'nameProperty': 'vtp_name', 'pill': 'primary'},
    '__dbg': {'title': 'Debug Mode', 'isBuiltIn': not False, 'pill': 'primary'},
    '__d': {'title': 'DOM Element', 'nameProperty': 'vtp_selectorType'},
    '__vis': {'title': 'Element Visibility'},
    '__f': {'title': 'HTTP Referrer', 'nameProperty': 'vtp_component'},
    '__j': {'title': 'Global JavaScript Variable', 'nameProperty': 'vtp_name'},
    '__smm': {'title': 'Lookup Table'},
    '__r': {'title': 'Random Number', 'isBuiltIn': not False, 'pill': 'primary'},
    '__remm': {'title': 'RegEx Table'},
    '__u': {'title': 'URL', 'nameProperty': 'vtp_component'},
    '__gas': {'title': 'Google Analytics Settings', 'pill': 'warning'},
    '__aev': {'title': 'Auto Event Variable', 'nameProperty': 'vtp_varType', 'pill': 'primary'},
    '__cid': {'title': 'Container ID', 'pill': 'primary', 'isBuiltIn': not False},
    '__awec': {'title': 'User-Provided Data', 'pill': 'primary'},
    '_custom_variable_template': {'title': 'Custom Variable Template', 'pill': 'dark'},
    '__t': {'title': 'Custom Firing Schedule Enabled'},
    '__hid': {'title': 'HTML ID', 'isBuiltIn': not False},
    '__uv': {'title': 'Undefined Value', 'pill': 'dark'}
}

triggers_index = {
    '__evl': {'title': "Element Visibility", 'pill': "primary", 'exportType': "ELEMENT_VISIBILITY"},
    '__cl': {'title': "Click", 'pill': "primary", 'exportType': "CLICK"},
    '__fsl': {'title': "Form Submit", 'pill': "primary", 'exportType': "FORM_SUBMISSION"},
    '__hl': {'title': "History Listener", 'pill': "primary", 'exportType': "HISTORY_CHANGE"},
    '__jel': {'title': "JavaScript Error", 'pill': "primary", 'exportType': "JS_ERROR"},
    '__lcl': {'title': "Link Click", 'pill': "primary", 'exportType': "LINK_CLICK"},
    '__sdl': {'title': "Scroll Depth Listener", 'pill': "primary", 'exportType': "SCROLL_DEPTH"},
    '__tl': {'title': "Timer", 'pill': "primary", 'exportType': "TIMER"},
    '__ytl': {'title': "YouTube Video Listener", 'pill': "primary", 'exportType': "YOU_TUBE_VIDEO"},
    "gtm.dom": {'title': "DOM Ready", 'pill': "primary", 'exportType': "DOM_READY"},
    "gtm.load": {'title': "Window Loaded", 'pill': "primary", 'exportType': "WINDOW_LOADED"},
    "gtm.js": {'title': "Page View", 'pill': "primary", 'exportType': "PAGEVIEW"},
    "gtm.click": {'title': "Click", 'pill': "primary", 'exportType': "CLICK"},
    "gtm.triggerGroup": {'title': "Trigger Group", 'pill': "secondary", 'exportType': "TRIGGER_GROUP"},
    "gtm.historyChange": {'title': "History Change", 'pill': "secondary", 'exportType': "HISTORY_CHANGE"},
    '__e': {'title': "Custom Event", 'pill': "warning", 'exportType': "CUSTOM_EVENT"},
    '__tg': {'title': "Trigger Group", 'pill': "secondary", 'exportType': "TRIGGER_GROUP"},
    'gtm.init_consent': {'title': 'Consent Initialization', 'pill': 'primary', 'exportType': "CONSENT INITIALIZATION"},
    'gtm.init': {'title': 'Initialization', 'pill': 'primary', 'exportType': "INITIALIZATION"}
}

evaluations_index = {
    '_cn': {'title': "contains", 'exportTitle': "CONTAINS"},
    '_css': {'title': "matches css selector", 'exportTitle': "CSS_SELECTOR'"},
    '_ew': {'title': "ends with", 'exportTitle': "ENDS_WITH'"},
    '_eq': {'title': "equals", 'exportTitle': "EQUALS"},
    '_ge': {'title': ">=", 'exportTitle': "GREATER_OR_EQUALS'"},
    '_gt': {'title': ">", 'exportTitle': "GREATER"},
    '_le': {'title': "<=", 'exportTitle': "LESS_OR_EQUALS'"},
    '_lt': {'title': "<", 'exportTitle': "LESS"},
    '_lc': {'title': "later"},
    '_re': {'title': "matches regex", 'exportTitle': "MATCH_REGEX'"},
    '_sw': {'title': "starts with", 'exportTitle': "STARTS_WITH'"},
    '_um': {'title': "url matches", 'exportTitle': "URL_MATCHES'"}
}

dlvBuiltins_index = {
    "gtm.element": {'title': "Click Element"},
    "gtm.elementClasses": {'title': "Click Classes"},
    "gtm.elementId": {'title': "Click ID"},
    "gtm.elementTarget": {'title': "Click Target"},
    "gtm.elementUrl": {'title': "Click URL"},
    "gtm.elementText": {'title': "Click Text"},
    "gtm.errorMessage": {'title': "Error Message"},
    "gtm.errorUrl": {'title': "Error URL"},
    "gtm.errorLineNumber": {'title': "Error Line"},
    "gtm.historyChangeSource": {'title': "History Source"},
    "gtm.newUrlFragment": {'title': "New History Fragment"},
    "gtm.newHistoryState": {'title': "New History State"},
    "gtm.oldUrlFragment": {'title': "Old History Fragment"},
    "gtm.oldHistoryState": {'title': "Old History State"},
    "gtm.scrollThreshold": {'title': "Scroll Depth Threshold"},
    "gtm.scrollUnits": {'title': "Scroll Depth Units"},
    "gtm.scrollDirection": {'title': "Scroll Depth Direction"},
    "gtm.videoCurrentTime": {'title': "Video Current Time"},
    "gtm.videoDuration": {'title': "Video Duration"},
    "gtm.videoPercent": {'title': "Video Percent"},
    "gtm.videoProvider": {'title': "Video Provider"},
    "gtm.videoStatus": {'title': "Video Status"},
    "gtm.videoTitle": {'title': "Video Title"},
    "gtm.videoUrl": {'title': "Video URL"},
    "gtm.videoVisible": {'title': "Video Visible"},
    "gtm.visibleRatio": {'title': "Element Visibility Ratio (Percent Visible)"},
    "gtm.visibleTime": {'title': "Element Visibility Time (On-Screen Duration)"}
}

runtime_index = {
    0: {'symbol': '+', 'type': 'operator', 'name': 'addition'},
    1: {'symbol': '&&', 'type': 'operator', 'name': 'logical AND'},
    2: {'symbol': '.', 'type': 'no type', 'name': 'method accessor'},
    3: {'symbol': '=', 'type': 'operator', 'name': 'assignment'},
    4: {'symbol': 'break', 'type': 'statement', 'name': 'break statement'},
    5: {'symbol': 'case', 'type': 'statement', 'name': 'case (switch)'},
    6: {'symbol': 'continue', 'type': 'statement', 'name': 'continue statement'},
    7: {'symbol': '[]', 'type': 'array', 'name': 'index based array'},
    8: {'symbol': '{}', 'type': 'array', 'name': 'key-value based array'},
    9: {'symbol': 'default', 'type': 'statement', 'name': 'default (switch)'},
    10: {'symbol': '/', 'type': 'operator', 'name': 'division'},
    11: {'symbol': '[]', 'type': '', 'name': ''},
    12: {'symbol': '==', 'type': 'operator', 'name': 'equality'},
    13: {'symbol': '[]', 'type': '', 'name': ''},
    14: {'symbol': '[]', 'type': '', 'name': ''},
    15: {'symbol': 'variable_reference', 'type': '', 'name': ''},
    16: {'symbol': '[]', 'type': 'no type', 'name': 'property accessor'},
    17: {'symbol': '.', 'type': 'no type', 'name': 'property accessor'},
    18: {'symbol': '>', 'type': 'operator', 'name': 'larger than'},
    19: {'symbol': '>=', 'type': 'operator', 'name': 'larger than or equal to'},
    20: {'symbol': '===', 'type': 'operator', 'name': 'equality with type comparison'},
    21: {'symbol': '!==', 'type': 'operator', 'name': 'NOT equality with type comparison'},
    22: {'symbol': 'if', 'type': 'statement', 'name': 'if statement'},
    23: {'symbol': '<', 'type': 'operator', 'name': 'less than'},
    24: {'symbol': '<=', 'type': 'operator', 'name': 'less than or equal to'},
    25: {'symbol': '%', 'type': 'operator', 'name': 'division reminder'},
    26: {'symbol': '*', 'type': 'operator', 'name': 'multiplication'},
    27: {'symbol': '-', 'type': 'operator', 'name': 'unary negation'},
    28: {'symbol': '!', 'type': 'operator', 'name': 'logical NOT'},
    29: {'symbol': '!=', 'type': 'operator', 'name': 'NOT equality'},
    30: {'symbol': '||', 'type': 'operator', 'name': 'logical OR'},
    31: {'symbol': '[]', 'type': '', 'name': ''},
    32: {'symbol': '[]', 'type': '', 'name': ''},
    33: {'symbol': '[]', 'type': '', 'name': ''},
    34: {'symbol': '[]', 'type': '', 'name': ''},
    35: {'symbol': '[]', 'type': '', 'name': ''},
    36: {'symbol': 'return', 'type': 'statement', 'name': 'return statement'},
    37: {'symbol': '-', 'type': 'operator', 'name': 'substraction'},
    38: {'symbol': 'switch', 'type': 'statement', 'name': 'switch statement'},
    39: {'symbol': '?', 'type': 'operator', 'name': 'ternary operator'},
    40: {'symbol': 'typeof', 'type': 'operator', 'name': 'Type return operator'},
    41: {'symbol': 'var', 'type': 'variable list', 'name': 'variable declaration var/let',
         'variations': {1: 'var list', 2: 'let list'}},
    42: {'symbol': 'while', 'type': 'statement', 'name': 'while and do...while statement',
         'variations': {1: 'while', 2: 'do...while'}},
    43: {'symbol': '[]', 'type': 'no type', 'name': 'Property setter'},
    44: {'symbol': 'undefined', 'type': 'statement', 'name': 'undefined statement'},
    45: {'symbol': 'null', 'type': 'null', 'name': 'null type'},
    46: [],
    47: {'symbol': 'for', 'type': 'statement', 'name': 'for statement',
         'variation': 'for (var a in b)'},
    48: [],
    49: {'symbol': 'control', 'type': 'statement', 'name': 'control statement'},
    50: {'symbol': 'function', 'type': 'declaration', 'name': 'function',
         'variation': 'function definition'},
    51: {'symbol': 'function', 'type': 'declaration', 'name': 'function',
         'variation': 'function assignment'},
    52: {'symbol': 'const', 'type': 'constant', 'name': 'constant declaration'},
    53: {'symbol': 'for', 'type': 'statement', 'name': 'for statement',
         'variation': 'standard'},
    54: [],
    55: {'symbol': 'for', 'type': 'statement', 'name': 'for statement',
         'variation': 'for (let a in b)'},
    56: {'symbol': '&', 'type': 'operator', 'name': 'Bitwise AND'},
    57: {'symbol': '<<', 'type': 'operator', 'name': 'Bitwise Leftshift'},
    58: {'symbol': '~', 'type': 'operator', 'name': 'Bitwise negation'},
    59: {'symbol': '|', 'type': 'operator', 'name': 'Bitwise OR'},
    60: {'symbol': '>>', 'type': 'operator', 'name': 'Bitwise rightshift'},
    61: {'symbol': '>>>', 'type': 'operator', 'name': 'Unsigned Bitwise rightshift'},
    62: {'symbol': '^', 'type': 'operator', 'name': 'Bitwise XOR'},
    63: [],
    64: [],
    65: {'symbol': 'for', 'type': 'statement', 'name': 'for statement',
         'variation': 'for (var a of b)'},
    66: {'symbol': 'for', 'type': 'statement', 'name': 'for statement',
         'variation': 'for (let a of b)'}
}
