tags_index = {
    '__paused': {
        'title': 'Paused Tag',
        'nameProperty': 'vtp_originalTagType',
        'pill': 'light'
    },
    '__abtGeneric': {'title': 'AB TASTY Generic Tag'},
    '__adm': {'title': 'Adometry Tag'},
    '__asp': {'title': 'AdRoll Smart Pixel Tag'},
    '__awct': {'title': 'Google Ads Conversion Tracking Tag'},
    '__sp': {'title': 'Google Ads Remarketing Tag'},
    '__awc': {'title': 'Affiliate Window Conversion Tag'},
    '__awj': {'title': 'Affiliate Window Journey Tag'},
    '__baut': {'title': 'Bing Ads Universal Event Tracking'},
    '__bb': {'title': 'Bizrate Insights Buyer Survey Solution'},
    '__bsa': {'title': 'Bizrate Insights Site Abandonment Survey Solution'},
    '__cts': {'title': 'ClickTale Standard Tracking Tag'},
    '__csm': {'title': 'comScore Unified Digital Measurement Tag'},
    '__gclidw': {'title': 'Conversion Linker'},
    '__cegg': {'title': 'Crazy Egg Tag'},
    '__crto': {'title': 'Criteo OneTag'},
    '__html': {
        'title': 'Custom HTML Tag',
        'infoKey': 'vtp_html'
    },
    '__img': {'title': 'Custom Image Tag'},
    '__dstag': {'title': 'DistroScale Tag'},
    '__flc': {'title': 'Floodlight Counter Tag'},
    '__fls': {'title': 'Floodlight Sales Tag'},
    '__m6d': {'title': 'Dstillery Universal Pixel Tag'},
    '__ela': {'title': 'Eulerian Analytics Tag'},
    '__ga': {
        'title': 'Google Analytics Tag',
        'pill': 'warning'
    },
    '__gcs': {'title': 'Google Consumer Surveys Website Satisfaction'},
    '__opt': {'title': 'Google Optimize'},
    '__ts': {'title': 'Google Trusted Stores Tag'},
    '__hjtc': {
        'title': 'Hotjar Tracking Code',
        'pill': 'danger'
    },
    '__infinity': {'title': 'Infinity Call Tracking Tag'},
    '__sca': {'title': 'Intent Media - Search Compare Ads'},
    '__k50Init': {'title': 'K50 tracking tag'},
    '__ll': {'title': 'LeadLab'},
    '__bzi': {'title': 'LinkedIn Tag'},
    '__ljs': {'title': 'Lytics JS Tag'},
    '__ms': {'title': 'Marin Software Tag'},
    '__mpm': {'title': 'Mediaplex - IFRAME MCT Tag'},
    '__mpr': {'title': 'Mediaplex - Standard IMG ROI Tag'},
    '__mf': {'title': 'Mouseflow Tag'},
    '__ndcr': {'title': 'Nielsen DCR Static Lite Tag'},
    '__nudge': {'title': 'Nudge Content Analytics Tag'},
    '__okt': {'title': 'Oktopost Tracking Code'},
    '__omc': {'title': 'Optimise Conversion Tag'},
    '__messagemate': {'title': 'OwnerListens Message Mate'},
    '__pa': {'title': 'Perfect Audience Pixel'},
    '__pc': {'title': 'Personali Canvas'},
    '__placedPixel': {'title': 'Placed'},
    '__pijs': {'title': 'Pulse Insights Voice of Customer Platform'},
    '__qcm': {'title': 'Quantcast Audience Measurement'},
    '__fxm': {'title': 'Rawsoft FoxMetrics'},
    '__scjs': {'title': 'SaleCycle JavaScript Tag'},
    '__scp': {'title': 'SaleCycle Pixel Tag'},
    '__sfc': {'title': 'SearchForce JavaScript Tracking for Conversion Page'},
    '__sfl': {'title': 'SearchForce JavaScript Tracking for Landing Page'},
    '__sfr': {'title': 'SearchForce Redirection Tracking Tag'},
    '__shareaholic': {'title': 'Shareaholic'},
    '__svw': {'title': 'Survicate Widget'},
    '__tdlc': {'title': 'Tradedoubler Lead Conversion Tag'},
    '__tdsc': {'title': 'Tradedoubler Sale Conversion Tag'},
    '__tc': {'title': 'Turn Conversion Tracking Tag'},
    '__tdc': {'title': 'Turn Data Collection Tag'},
    '__twitter_website_tag': {'title': 'Twitter Universal Website Tag'},
    '__ua':
        {'title': 'Universal Analytics Tag',
         'nameProperty': 'vtp_trackType',
         'pill': 'warning'
         },
    '__uslt': {'title': 'Upsellit Global Footer Tag'},
    '__uspt': {'title': 'Upsellit Confirmation Tag'},
    '__vei': {'title': 'Ve Interactive JavaScript Tag'},
    '__veip': {'title': 'Ve Interactive Pixel'},
    '__vdc': {'title': 'VisualDNA Conversion Tag'},
    '__xpsh': {'title': 'Xtremepush'},
    '__yieldify': {'title': 'Yieldify'},
    '__qpx': {'title': 'Quora'},
    '__pntr': {'title': 'Pinterest'}
}

macros_index = {
    '__k': {'title': '1st Party Cookie', 'nameProperty': 'vtp_name'},
    '__c': {'title': 'Constant', 'nameProperty': 'vtp_value'},
    '__ctv': {'title': 'Container Version', 'isBuiltIn': not False, 'pill': 'primary'},
    '__e': {'title': 'Event', 'isBuiltIn': not False, 'pill': 'primary'},
    '__jsm': {'title': 'Custom JavaScript Variable', 'infoKey': 'vtp_javascript'},
    '__v': {'title': 'Data Layer Var', 'nameProperty': 'vtp_name', 'pill': 'primary'},
    '__dbg': {'title': 'Debug Mode', 'isBuiltIn': not False, 'pill': 'primary'},
    '__d': {'title': 'DOM Element', 'nameProperty': 'vtp_selectorType'},
    '__vis': {'title': 'Element Visibility'},
    '__f': {'title': 'HTTP Referrer', 'nameProperty': 'vtp_component'},
    '__j': {'title': 'Global JavaScript Variable', 'nameProperty': 'vtp_name'},
    '__smm': {'title': 'Lookup Table'},
    '__r': {'title': 'Random Number', 'isBuiltIn': not False, 'pill': 'primary'},
    '__remm': {'title': 'RegEx Table'},
    '__u': {'title': 'URL', 'nameProperty': 'vtp_component'},
    '__gas': {'title': 'Google Analytics Settings', 'pill': 'warning'},
    '__aev': {'title': 'Auto Event Variable', 'nameProperty': 'vtp_varType', 'pill': 'primary'},
    '__cid': {'title': 'Container ID', 'pill': 'primary', 'isBuiltIn': not False}
}

triggers_index = {
    '__evl': {'title': "Element Visibility", 'pill': "primary", 'exportType': "ELEMENT_VISIBILITY"},
    '__cl': {'title': "Click", 'pill': "primary", 'exportType': "CLICK"},
    '__fsl': {'title': "Form Submit", 'pill': "primary", 'exportType': "FORM_SUBMISSION"},
    '__hl': {'title': "History Listener", 'pill': "primary", 'exportType': "HISTORY_CHANGE"},
    '__jel': {'title': "JavaScript Error", 'pill': "primary", 'exportType': "JS_ERROR"},
    '__lcl': {'title': "Link Click", 'pill': "primary", 'exportType': "LINK_CLICK"},
    '__sdl': {'title': "Scroll Depth Listener", 'pill': "primary", 'exportType': "SCROLL_DEPTH"},
    '__tl': {'title': "Timer", 'pill': "primary", 'exportType': "TIMER"},
    '__ytl': {'title': "YouTube Video Listener", 'pill': "primary", 'exportType': "YOU_TUBE_VIDEO"},
    "gtm.dom": {'title': "DOM Ready", 'pill': "primary", 'exportType': "DOM_READY"},
    "gtm.load": {'title': "Window Loaded", 'pill': "primary", 'exportType': "WINDOW_LOADED"},
    "gtm.js": {'title': "Page View", 'pill': "primary", 'exportType': "PAGEVIEW"},
    "gtm.click": {'title': "Click", 'pill': "primary", 'exportType': "CLICK"},
    "gtm.triggerGroup": {'title': "Trigger Group", 'pill': "secondary", 'exportType': "TRIGGER_GROUP"},
    "gtm.historyChange": {'title': "History Change", 'pill': "secondary", 'exportType': "HISTORY_CHANGE"},
    '__e': {'title': "Custom Event", 'pill': "warning", 'exportType': "CUSTOM_EVENT"},
    '__tg': {'title': "Trigger Group", 'pill': "secondary", 'exportType': "TRIGGER_GROUP"}
}

evaluations_index = {
    '_cn': {'title': "contains", 'exportTitle': "CONTAINS"},
    '_css': {'title': "matches css selector", 'exportTitle': "CSS_SELECTOR'"},
    '_ew': {'title': "ends with", 'exportTitle': "ENDS_WITH'"},
    '_eq': {'title': "equals", 'exportTitle': "EQUALS"},
    '_ge': {'title': ">=", 'exportTitle': "GREATER_OR_EQUALS'"},
    '_gt': {'title': ">", 'exportTitle': "GREATER"},
    '_le': {'title': "<=", 'exportTitle': "LESS_OR_EQUALS'"},
    '_lt': {'title': "<", 'exportTitle': "LESS"},
    '_lc': {'title': "later"},
    '_re': {'title': "matches regex", 'exportTitle': "MATCH_REGEX'"},
    '_sw': {'title': "starts with", 'exportTitle': "STARTS_WITH'"},
    '_um': {'title': "url matches", 'exportTitle': "URL_MATCHES'"}
}

dlvBuiltins_index = {
    "gtm.element": {'title': "Click Element"},
    "gtm.elementClasses": {'title': "Click Classes"},
    "gtm.elementId": {'title': "Click ID"},
    "gtm.elementTarget": {'title': "Click Target"},
    "gtm.elementUrl": {'title': "Click URL"},
    "gtm.elementText": {'title': "Click Text"},
    "gtm.errorMessage": {'title': "Error Message"},
    "gtm.errorUrl": {'title': "Error URL"},
    "gtm.errorLineNumber": {'title': "Error Line"},
    "gtm.historyChangeSource": {'title': "History Source"},
    "gtm.newUrlFragment": {'title': "New History Fragment"},
    "gtm.newHistoryState": {'title': "New History State"},
    "gtm.oldUrlFragment": {'title': "Old History Fragment"},
    "gtm.oldHistoryState": {'title': "Old History State"},
    "gtm.scrollThreshold": {'title': "Scroll Depth Threshold"},
    "gtm.scrollUnits": {'title': "Scroll Depth Units"},
    "gtm.scrollDirection": {'title': "Scroll Depth Direction"},
    "gtm.videoCurrentTime": {'title': "Video Current Time"},
    "gtm.videoDuration": {'title': "Video Duration"},
    "gtm.videoPercent": {'title': "Video Percent"},
    "gtm.videoProvider": {'title': "Video Provider"},
    "gtm.videoStatus": {'title': "Video Status"},
    "gtm.videoTitle": {'title': "Video Title"},
    "gtm.videoUrl": {'title': "Video URL"},
    "gtm.videoVisible": {'title': "Video Visible"},
    "gtm.visibleRatio": {'title': "Element Visibility Ratio"},
    "gtm.visibleTime": {'title': "Element Visibility Time"}
}

skip_macro_keys = ['title', 'isBuiltin', 'pill', 'nameProperty', 'function']
skip_tag_keys = ['pill', 'property', 'nameProperty', 'title', 'function', 'infoKey', 'teardown_tags',
                 'setup_tags', '_sequence']
triggers_not_tags = ['__tl', '__tg', '__cl', '__lcl']
code_snippet_properties = ['vtp_html', 'vtp_javascript']
